### ISSUE TITLE
Transcription verification recruiting & training

### ISSUE THREAD

**Issue by Baleja** [civictechindex/BOP#74]
### Overview
To provide training to new recruits for the transcription verification procedure.

### Action Items
- [ ]  Create & send messaging to recruit transcribers #175 
- [x]  Create Interview Transcription Verification Procedure document
- [x]  Schedule a training session

### Resources/Instructions
[Interview transcription verification procedure](https://docs.google.com/document/u/1/d/1kTrslqYY0whUjCMxbcV7Ft1nzCr_UTPWXfhomNgOvEw/edit)
[Messaging for Transcriber Recruitment](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit)

[ New Transcription Verification Instructions](https://docs.google.com/document/d/1mmwozE1kpQCG3O6eSEO1BSyHeSbX7xeT9pYZZBEl98o/edit#heading=h.spmxg8vntlm1rl)
[Fake Wonder Woman Sheet](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923)
[Understanding columns](https://docs.google.com/document/d/1WDlb7lpDhrS6QGGPIQjzfHUE1tvFI4Ky0drQl-fT01Q/edit#heading=h.8cecuqj0l43c)
[ BOP Extension Project :Transcription Verification Training ](https://docs.google.com/presentation/d/1wuq7am4UW7P4k2wG41yreQUBePwBe47MO60sW1-vm54/edit#slide=id.gbc15626aa8_2_23)

**Comment by MasSamH** [comment]
@MarianneAnthonette 
[ ] Fast track to create messaging for 29th Dec.

**Comment by MarianneAnthonette** [comment]
Created an initial draft of [messaging for Transcriber Recruitment](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit). Did not include CTA and need help thinking of what this volunteer opportunity benefits (for the volunteer's end).

**Comment by Baleja** [comment]
Progress: Messaging creating, looking at dates to schedule training for new recruits, Mari is making a deck for training.

**Comment by Baleja** [comment]
Progress: Raquel is creating documentation for training, deck & google doc.

**Comment by raquelnish** [comment]
Continuing the development of a slide deck & script of transcription training. Expect to have the first version of it on Saturday.

**Comment by raquelnish** [comment]
After feedback on Saturday, I will:
1. Add more slides to the deck to go through the topic: Self-assigning &updating the GitHub issue with a few screenshots, a quick video, and refer to ou wiki where we can store images and videos.
2. Give up on giant text 'Self-assigning &updating GitHub': Might use it as a video script and a bit of the content to suggest updates to the GitHub issue template. Suggestions in _italic_ below:

**Overview**
For UXR team, we need to process & analyze Interview number 40 in order to complete our analysis phase. Interview length (m:s) 37:08. _It takes almost twice the length of time to do the Transcription Verification._ 

**Action Items**
 This brigade interview needs the following work done:
- [ ] 1. Transcription verification 
    - [ ]  _Move this issue from the ‘Prioritizes Backlog’ to the ‘In progress backlog’_
    - [ ]  Add data organization label & remove transcription verification label
- [ ] 2. Data organization
    - [ ]  Add coding label & remove data organization label.
- [ ]  3. Coding
    - [ ]  Add tagging label & remove coding label.
- [ ] 4. Tagging 
   - [ ]  _Move this issue to the ‘Done’ Column our board_

**Reporting progress**
Add a note in the comments with details _adding the team lead handle @_

3. I am also working on the Transcription Verification Training, which so far is very detailed. I will try to follow the same idea: screenshots at the slide deck, maybe small videos about some topics

 @MarianneAnthonette maybe you could take a look at this [BOP UXR Training Transcription Verification](https://docs.google.com/document/d/1OAcajI7_cotpzYN9q7ALECab6YOKnWIz8UHkBvSoopM/edit) which I made originally as a script for a video, but maybe could be used to update the actual Transcription Verification Sheet. If you edit/ take things out, could you ~~strikethrough~~ and if you add change color? Because it will be easier for me to see and edit my actual script sheet (I have another googledoc!)

**Comment by ExperimentsInHonesty** [comment]
@raquelnish will update the screenshots to clean out the excess text

**Comment by raquelnish** [comment]
### Overview
For UXR team, we need to process & analyze Interview number [insert number here] in order to complete our analysis phase. 

### Instructions for working this issue
Do the action items defined by the checkboxes. Each numbered step is a discrete task. We encourage you to complete all the tasks for this brigade's interview, however, you can stop after any of the numbered tasks.

### Action Items
- [ ] Assign yourself to this issue (see animated GIF below) 
- [ ] Move this issue from the ‘Prioritized Backlog’ to ‘In progress’ (see animated GIF below) 
#### This brigade interview needs the following work done:
- [ ] 1. Transcription verification 
    - [ ]  Add data organization label & remove transcription verification label
- [ ] 2. Data organization
    - [ ]  Add coding label & remove data organization label.
- [ ]  3. Coding
    - [ ]  Add tagging label & remove coding label.
- [ ] 4. Tagging 
   - [ ]  Mark this issue as Done by clicking the button on the bottom of the issue  
![Screen Shot 2021-01-26 at 10 41 35 AM](https://user-images.githubusercontent.com/37763229/105889502-16c1e780-5fc3-11eb-8473-f2319059c719.png)

### Reporting progress
- Be sure to check the box when you finish an action item.
- Report your progress weekly in a comment below using the following format:
     - Progress: 
     - Blockers: 
     - Availability :
     - Estimated date of completion:

### Stopping mid issue 
#### Reasons: 
- Got personally busy, can’t finish
-  Only want to do a specific type of task per interview
- There is a blocker (e.g. instructions not ready yet) in the way of finishing and I still have time to work on other issues 
#### What to do if you have to stop working mid issue:
- Note your progress in the checkboxes 
- Add a note in the comments with details
- Move the issue to the questions/review column 

### Unassigning yourself from this issue
If you are finished with one of the 4 Action Items and you are not going to do the next one
- [ ] Move this issue from the ‘In progress’ to the ‘Prioritized Backlog’(see animated GIF below) 
- [ ] Unassign yourself from this issue (see animated GIF below) 

### Resources/Instructions
[Interview Data Sheet][insert url]
[Transcription Verification Instructions](https://docs.google.com/document/d/1kTrslqYY0whUjCMxbcV7Ft1nzCr_UTPWXfhomNgOvEw/edit)
[Data Organization Instructions](https://docs.google.com/document/d/1vJqDQ8Th8kSgisSSiMzDpRHTIWI3ILCX4eOTgMwRdoY/edit)
[Coding Instructions](https://docs.google.com/document/u/0/d/10am6Ki0gJKzITt2kcjMsR233oC_9WJneKnFimFc8Mao/edit)
[Tagging Instructions](https://docs.google.com/document/d/1soNmLMyVspkgz2MMD5DuF_WVBBmnFLFgCPNZDjxjDWI/edit#)

#### Assign & Unassign yourself to this issue
![Assign & Unassign](http://g.recordit.co/MkwqNlnWWO.gif)

####  Move this issue from the ‘Prioritized Backlog’ to the ‘In progress’ & back
![Prioritized to In progress & back](http://g.recordit.co/wvXm85TR1Q.gif)

**Comment by raquelnish** [comment]
What about trying a self-training for new UXRs?

Use the Deck to redirect to other sources:
-  What is Code for America/ What is a Brigade (Serena's explanation)/ What is the goal of this project? Project´s stages
- Interviews: how were they conducted? What is our objective?
- Goal of Transcription verification
- What do you need to join our time? Onboarding Slack/GitHub/UXR number:  link to our wiki for step by step process
- How do you start working?  
    -Link to GitHub video (how to assign/unassign/update)
    -Link to Transcription Verification training video
    -Google doc Transcription Verification Instructions
    -Link to open book quizz with 10 questions / multiple answers/ has to pass with 100%/ google form
    -Once you pass the quiz/slack us/ get your UXR number/ get access to our  board /starts working
    
  Videos could be stored in HACK4LA You Tube channel?

**Comment by raquelnish** [comment]
I will update all the existing issues at the prioritized backlog to have the new instructions

**Comment by raquelnish** [comment]
Transcription Verification Self- Training:
I will create all material for the new UXRs self-onboarding and training.

They will receive a link to a Slide Deck  with the following information:

- [ ] What is Code for America/ What is a Brigade (Serena's explanation)/ What is the goal of this project? Project´s stages
- [ ] Interviews: how were they conducted? What is our objective?
- [ ] The goal of Transcription verification
- [ ] What do you need to join our team? Onboarding Slack/GitHub/UXR number: link to our wiki for step by step process
- [ ] Link to GitHub video (how to assign/unassign/update) on YouTube
- [ ] Link to Transcription Verification tutorial  video on YouTube
- [ ] Link to How to use Otter.ai on YouTube
- [ ] Updated Transcription Verification Instructions
- [ ] Link to open-book quiz with 10 questions / multiple answers/ has to pass with 100%/ Once they pass the quiz/slack us/ get your UXR number/ get access to our board /starts working

Updtates:
-Waiting for YouTube login/ password
-Transcription Verification tutorial video was recorded. It's 27 min long. Mari made some comments to change a couple of things will do it.
-Transcription Verification Instructions were updated. Check with Mari if it is OK to update the current issues link

**Comment by MarianneAnthonette** [comment]
@raquelnish Quiz log-in doesn't work. We also shouldn't have the password here, must be moved to 1password.

**Comment by Baleja** [comment]
Progress: almost finished with training materials, bonnie will test the deck thursday to see if new people will come across any blockers.

**Comment by MarianneAnthonette** [comment]
Quiz has been reviewed and updated.

**Comment by Baleja** [comment]
Raquel to send bonnie a self training appointment for Friday at noon for test driving the training material.

**Comment by Baleja** [comment]
@MarianneAnthonette Please share the UXR air-table communities we can reach out to once the training is completed. Once we have more people we will be able to conduct analysis #153

**Comment by MarianneAnthonette** [comment]
A few communities to recruit UXRs (I know a bunch more):
- HackforLA (Slack - duh)
- Mixed Methods (Slack)
- Design Gigs for Good (Slack)
- DesignBuddies (Discord - if you want more driven young'uns)
- UX Beginner: Design Community (FB)

**Comment by raquelnish** [comment]
We are aiming to have 3 more UXRs to complete the transcription verification training to help complete the interview transcription.
Coding will need to be done within a group to make sense of the ever adapting language.
As soon as bonnie OKs self training we should start recruiting.

**Comment by raquelnish** [comment]
Look at the training material checklist above:
Progress: Will have to record GitHub video again/ Transcription Verification will have screenshots+ small videos. Will no longer be 30min video training.
Blockers: Waiting for the decision on transcription sheet changes: color, titles, ranking 0 to 6 (Superman form test), CONT(A) solution for ranking area not to be blank
Availability:  10h week
Estimate Date Completion: Saturday, February 12nth

**Comment by Baleja** [comment]
So as someone who is actively using the instructions documents, I think for the new UXRS it would be great to add understanding objectives at the beginning so as not to get too confused and leave the transcription half way. This will show them exactly what they are benefiting from during this very long process.
Something along the lines of: 
In this section you will learn:
- How to conduct, record and report first hand source material
- How to differentiate ideas from sentiment in natural language
- How to consolidate multiple interviews

**Comment by raquelnish** [comment]
Rewriting the Transcription Verification Instructions:
- Bonnie made changes to the transcription sheet template that Thad said was Ok
- I changed the screenshots until this item:  Step 7. Column D ‘Interviewee text after your edits’ 
- [ ] The section 'Understanding the columns' will be in a separate doc/I still need to edit it
- [ ]  Bonnie will check the work until now
- [ ] I will edit a video to add it to the explanation about Cell53 
- [ ] Create images/ instructions or videos for Column D ‘Interviewee text after your edits’ 
- [ ] Figure out how to offer the list of instructions regarding editing the test at the end of the google doc ( 1 to 14)

Resources:
[ New Transcription Sheet](https://docs.google.com/document/d/1mmwozE1kpQCG3O6eSEO1BSyHeSbX7xeT9pYZZBEl98o/edit#heading=h.spmxg8vntlm1rl)
[Fake Wwonder Woman Sheet](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923)
[Understanding columns](https://docs.google.com/document/d/1WDlb7lpDhrS6QGGPIQjzfHUE1tvFI4Ky0drQl-fT01Q/edit#heading=h.8cecuqj0l43c)

**Comment by raquelnish** [comment]
### Overview
Some changes were made to the transcription sheet template while iterating on the training material. Check issue #167 

### Dependencies
Have OtterAI working again so the team can:
- Record Fake Interview on OtterAI to use as part of the training material.
- Create a Fake Transcription Sheet with full fake information.
- Use both OtterAI fake interview link and Fake sheet to record a brief video showing how to use OtterA.I
- Take new screenshots of Fake Transcription  Sheet
### Action Items
- [ ] Record Fake Interview on OtterAI: I have created a sheet with things this Fake Interview should have to serve as examples for the training. It is called " Fake Interview must have".
- [ ] Record Otter AI tips video
- [ ] Take new screenshots of Fake Transcription  Sheet
- [ ] Send the training to new people to test it out

### Resources/Instructions
[Transcription Sheet Template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit?usp=sharing)
[Fake Interview must have](https://docs.google.com/spreadsheets/d/1xcNjdBBauaM6TfDw2Ha9eyIBaexURrNVRfEXCZmskTU/edit#gid=671198979)
[ BOP Extension Project: Transcription Verification Training](https://docs.google.com/presentation/d/1wuq7am4UW7P4k2wG41yreQUBePwBe47MO60sW1-vm54/edit#slide=id.ga0e9302c6f_0_19)
[Wonder Woman Sheet: ](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923) It is the one currently being used by anyone taking the training. It has the OtterAI link and text from a real Interview from Irit Seligman

**Comment by Baleja** [comment]
Need to add where to find the form, questions and sheet in the Conducting Interview Deck
